// frontend/src/views/games/About.vue
<template>
  <ActionModal
      v-if="showLocked" type="lock" :title="lockedText"
      @close="() => {showLocked = false}"
      @submit="() => {showLocked = false}">
  </ActionModal>
  <div
      class="flex flex flex-col gap-1 md:gap-3 pt-[25%] md:justify-end bg-cover h-full w-full min-h-full bg-bottom md:bg-left-bottom"
      :style="`background-image: url('${game_images[game_alias].background}')`">
    <div class="text-largest font-bold md:font-semibold text-content-secondary md:text-content-primary uppercase px-6 md:px-12"> {{
        game.title
      }}
    </div>
    <div class="flex flex-col items-center md:flex-row h-full md:h-fit gap-medium md:py-6 md:mb-12
    md:bg-bg-transparent-2 md:pl-12 md:pr-3 justify-between md:justify-normal">
      <div id="description" class="flex flex-col gap-small w-full px-6 md:px-0 md:w-[45%]">
        <div class="sm:text-base lg:text-xl text-content-secondary md:text-content-primary whitespace-pre-wrap">
          {{ game.short_description }}
        </div>
        <div id="tags" class="flex flex-row gap-2">
          <div v-for="data in gameData" :key="data"
               class="flex sm:text-sm md:text-lg lg:text-xl text-content-secondary md:text-content-primary p-1 lg:p-2
               min-h-[40px] md:min-h-none justify-center items-center bg-content-disabled-transparent text-center w-full rounded-sm">
            {{ data }}
          </div>
        </div>
      </div>
      <div class="flex flex-col md:flex-row w-full items-center gap-large justify-between md:gap-[5%]">
        <div class="flex flex-row w-full justify-between md:justify-normal md:gap-[5%]">
          <div id="links" class="flex flex-col gap-6 justify-center">
            <div v-for="link in links" :key="link" @click="link.locked ? lockedSection(link.lockedText) : link.link()"
                 class="flex flex-row p-3 pl-6 pr-12 md:!p-0 gap-xs text-large uppercase font-semibold items-center
               cursor-pointer bg-bg-transparent-2 md:bg-transparent rounded-sm"
                 :class="link.locked ? 'text-content-disabled' : 'hover:text-content-accent'">
              {{ link.title }}
              <inline-svg v-if="link.locked" class="h-6 w-6 text-content-disabled"
                          :src="require('@/assets/images/icons/common/lock.svg')"/>
            </div>
          </div>
          <inline-svg v-if="!phoneScreen && game_images[game_alias].logo"
                      :src="game_images[game_alias].logo" class="h-full"/>
          <img v-if="phoneScreen && game_images[game_alias].logo"
               :src="game_images[game_alias].logo_half" class="h-full"/>
        </div>
        <div id="other_games" @click="otherGames()"
             class="flex flex-row gap-xs items-center md:w-[15%] md:min-w-[150px] md:justify-end cursor-pointer">
          <div class="hidden md:flex text-medium text-right"> Какие-то<br>игры</div>
          <inline-svg class="h-12 w-12 rotate-90 md:rotate-0" :src="require('@/assets/images/icons/common/arrow.svg')"/>
        </div>
      </div>
    </div>
  </div>
</template>


<script setup lang="ts">
import {computed, ref} from "vue"
import ActionModal from "@/components/ActionModal.vue";
import {useStore} from "vuex";
import {useRouter} from "vue-router";
import {game_images} from "@/constants/gameImages";
import {formatDateRange} from "@/utils/dates";

const store = useStore()
const router = useRouter()
const props = defineProps(['game_alias'])
const user = store.getters['auth/user']
const showLocked = ref(false)
const lockedText = ref('')


const game = computed(() => store.getters['games/games'][props.game_alias])
const gameData = computed(() => [
  `${formatDateRange(new Date(game.value.start), new Date(game.value.end))} ${game.value.year}`,
  game.value.location, `${game.value.player_count} чел`,
])

const links = computed(() => [
  {
    link: () => router.push(`/account/${props.game_alias}/application`),
    locked: !user.mg && !game.value.open_applications,
    lockedText: 'Заявки еще/уже не принимаются',
    title: 'Заявка',
  },
  {
    link: () => router.push(`/game/${props.game_alias}/roles`),
    locked: !user.mg && !game.value.open_character_list,
    lockedText: "Сетка ролей еще не открыта",
    title: 'Сетка ролей',
  },
  {
    link: () => window.open(game.value.vk, '_blank').focus(),
    title: 'Группа ВК',
  },
])
const lockedSection = (lockedSectionText) => {
  lockedText.value = lockedSectionText
  showLocked.value = true
}

const otherGames = () => router.push(`/game/${{'whales': 'frostpunk', 'frostpunk': 'whales'}[props.game_alias]}/about`)


const phoneScreen = computed(() => window.screen.width < 768)
</script>

// frontend/src/features/games/About.tsx
import { useState } from 'react'
import { Link, useLoaderData } from 'react-router'
import type { gameLoader } from '../../app/data'
import { useRoot } from '../../app/Shell'
import { gameImages, whaleLogo } from '../../shared/assets'
import whaleHalf from '../../assets/images/logo/whales-half.png'
import { Icon, LockedDialog } from '../../shared/Navigation'
import { publicLink } from '../../shared/api/client'

function dateRange(start: string | null, end: string | null, year: number | null) {
  if (!start || !end) return year ? String(year) : ''
  const a = new Date(start), b = new Date(end)
  const months = ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек']
  return a.getDate() + (a.getMonth() === b.getMonth() ? '-' : ' ' + months[a.getMonth()] + ' - ') + b.getDate() + ' ' + months[b.getMonth()] + ' ' + year
}
export function Component() {
  const { game } = useLoaderData<typeof gameLoader>()
  const { user, games } = useRoot()
  const [locked, setLocked] = useState('')
  const other = games.find(other => other.alias !== game.alias)
  const links = [
    { title: 'Заявка', to: '/account/' + game.alias + '/application', locked: !user?.mg && !game.open_applications, message: 'Заявки еще/уже не принимаются' },
    { title: 'Сетка ролей', to: '/game/' + game.alias + '/roles', locked: !user?.mg && !game.open_character_list, message: 'Сетка ролей еще не открыта' },
  ]
  return <main className={'hero hero--' + game.alias} style={{ backgroundImage: 'url(' + gameImages(game.alias).background + ')' }}>
    <h1>{game.title}</h1>
    <div className="hero-band">
      <div className="hero-description"><p className="lead preserve">{game.short_description}</p>
        <ul className="facts"><li>{dateRange(game.start, game.end, game.year)}</li><li>{game.location}</li><li>{game.player_count} чел</li></ul>
      </div>
      <div className="hero-navigation"><div className="hero-links-logo">
        <nav className="hero-links" aria-label="Об игре">
          {links.map(link => link.locked
            ? <button key={link.title} className="locked" onClick={() => setLocked(link.message)}>{link.title}<Icon name="common/lock" /></button>
            : <Link key={link.title} to={link.to}>{link.title}</Link>)}
          {publicLink(game.vk, 'vk') && <a href={publicLink(game.vk, 'vk')} target="_blank" rel="noreferrer">Группа ВК</a>}
        </nav>
        {game.alias === 'whales' && <><img className="whale-logo" src={whaleLogo} alt="" />
          <img className="whale-half" src={whaleHalf} alt="" /></>}
      </div>
      {other && <Link className="other-games" to={'/game/' + other.alias + '/about'} aria-label={'Какие-то игры: ' + other.title}>
        <span>Какие-то<br />игры</span><Icon name="common/arrow" /></Link>}
      </div>
    </div>
    {locked && <LockedDialog title={locked} onClose={() => setLocked('')} />}
  </main>
}
