// frontend/src/features/games/About.tsx
import { useState } from 'react'
import { Link, useLoaderData } from 'react-router'
import type { gameLoader } from '../../app/data'
import { useRoot } from '../../app/Shell'
import { gameImages, whaleLogo } from '../../shared/assets'
import whaleHalf from '../../assets/images/logo/whales-half.png'
import { Icon, LockedDialog } from '../../shared/Navigation'
import { publicLink } from '../../shared/api/client'

function dateRange(start: string | null, end: string | null, year: number | null) {
  if (!start || !end) return year ? String(year) : ''
  const a = new Date(start), b = new Date(end)
  const months = ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек']
  return a.getDate() + (a.getMonth() === b.getMonth() ? '-' : ' ' + months[a.getMonth()] + ' - ') + b.getDate() + ' ' + months[b.getMonth()] + ' ' + year
}
export function Component() {
  const { game } = useLoaderData<typeof gameLoader>()
  const { user, games } = useRoot()
  const [locked, setLocked] = useState('')
  const other = games.find(other => other.alias !== game.alias)
  const links = [
    { title: 'Заявка', to: '/account/' + game.alias + '/application', locked: !user?.mg && !game.open_applications, message: 'Заявки еще/уже не принимаются' },
    { title: 'Сетка ролей', to: '/game/' + game.alias + '/roles', locked: !user?.mg && !game.open_character_list, message: 'Сетка ролей еще не открыта' },
  ]
  return <main className={'hero hero--' + game.alias} style={{ backgroundImage: 'url(' + gameImages(game.alias).background + ')' }}>
    <h1>{game.title}</h1>
    <div className="hero-band">
      <div className="hero-description"><p className="lead preserve">{game.short_description}</p>
        <ul className="facts"><li>{dateRange(game.start, game.end, game.year)}</li><li>{game.location}</li><li>{game.player_count} чел</li></ul>
      </div>
      <div className="hero-navigation"><div className="hero-links-logo">
        <nav className="hero-links" aria-label="Об игре">
          {links.map(link => link.locked
            ? <button key={link.title} className="locked" onClick={() => setLocked(link.message)}>{link.title}<Icon name="common/lock" /></button>
            : <Link key={link.title} to={link.to}>{link.title}</Link>)}
          {publicLink(game.vk, 'vk') && <a href={publicLink(game.vk, 'vk')} target="_blank" rel="noreferrer">Группа ВК</a>}
        </nav>
        {game.alias === 'whales' && <><img className="whale-logo" src={whaleLogo} alt="" />
          <img className="whale-half" src={whaleHalf} alt="" /></>}
      </div>
      {other && <Link className="other-games" to={'/game/' + other.alias + '/about'} aria-label={'Какие-то игры: ' + other.title}>
        <span>Какие-то<br />игры</span><Icon name="common/arrow" /></Link>}
      </div>
    </div>
    {locked && <LockedDialog title={locked} onClose={() => setLocked('')} />}
  </main>
}

// frontend/src/views/games/game/About.vue
<template>
  <ActionModal
      v-if="showLocked" type="lock"
      @close="() => {showLocked = false}"
      @submit="() => {showLocked = false}"
      :title="lockedText" :buttonText="$t('common.actions.ok')">
  </ActionModal>
  <div class="flex flex flex-col gap-6 justify-end bg-cover h-full w-full min-h-full"
       :style="`background-image: url('${game_images[alias].background}')`">
    <div class="text-8xl font-semibold px-12"> {{ game.title.toUpperCase() }}</div>
    <div class="flex flex-col mb-12 bg-bg-transparent-2 pl-12 pr-6">
      <div class="flex flex-row gap-6 py-6 justify-between">
        <div class="flex flex-row gap-24 w-3/5">
          <div class="flex flex-col gap-3 w-1/2">
            <div class="text-xl whitespace-pre-wrap"> {{ game.short_description }}</div>
            <div class="flex flex-row gap-2">
              <div v-for="data in gameData" :key="data"
                   class="bg-content-disabled-transparent text-md text-center w-full p-3 rounded-sm">
                {{ data }}
              </div>
            </div>
          </div>
          <div class="flex flex-col gap-3 w-1/2 justify-center">
            <div v-for="link in links" :key="link" @click="link.locked ? lockedSection(link.lockedText) : link.link()"
                 class="flex flex-row gap-1 text-4xl font-semibold items-center cursor-pointer"
                 :class="link.locked ? 'text-content-disabled' : 'hover:text-content-accent'">
              {{ link.title.toUpperCase() }}
              <inline-svg v-if="link.locked" class="h-6 w-6 text-content-disabled"
                          :src="require('@/assets/images/icons/common/lock.svg')"/>
            </div>
          </div>
        </div>
        <div @click="otherGames" class="flex flex-row gap-1 text-xl text-right items-center cursor-pointer">
          Какие-то<br> игры
          <inline-svg class="h-12 w-12" :src="require('@/assets/images/icons/common/arrow.svg')"/>
        </div>
      </div>
    </div>
  </div>
</template>


<script setup>
import {computed, ref} from "vue"
import gamesService from "@/services/gamesService";
import ActionModal from "@/components/ActionModal.vue";
import {useStore} from "vuex";
import {useRouter} from "vue-router";
import {game_images} from "@/constants/gameImages";
import {formatDateRange} from "@/utils/dates";

const store = useStore()
const router = useRouter()
const props = defineProps(['alias'])
const user = store.getters['auth/user']
const showLocked = ref(false)
const lockedText = ref('Раздел в разработке')

const lockedSection = (text) => {
  lockedText.value = text
  showLocked.value = true
}
const game = ref({
  id: 1,
  title: "lorem ipsum",
  image: null,
  vk: "",
})
gamesService.game(props.alias).then(({data}) => {
  game.value = data
})

const gameData = computed(() => [
  `${formatDateRange(new Date(game.value.start), new Date(game.value.end))} ${game.value.year}`,
  game.value.location, `${game.value.player_count} чел`,
])

const links = computed(() => {
  return [
    {
      link: () => router.push(`/game/${game.value.alias}/apply`),
      locked: !user.mg && !game.value.open_applications,
      lockedText: 'Заявки еще/уже не принимаются',
      title: 'Заявка',
    },
    {
      link: () => router.push(`/game/${game.value.alias}/roles`),
      locked: !user.mg && !game.value.open_character_list,
      lockedText: "Сетка ролей еще не открыта",
      title: 'Сетка ролей',
    },
    {
      link: () => window.open(game.value.vk, '_blank').focus(),
      title: 'Группа ВК',
    },
  ]
})

const otherGames = () => window.open(
    `/game/${{'whales': 'frostpunk', 'frostpunk': 'whales'}[props.alias]}/about`,
    '_blank'
).focus();
</script>
